### PR TITLE
friendly-login-time

### LINKED ISSUE #89: .exa - display the total login time in a more friendly manner
Someone having 3 months, 10 days, 5 hours and 2 minutos of total login time will show as "3 mon", on .exa... which is not very friendly.

### PR DESCRIPTION
**Pull request by subhamskm**
Fixes #89

### CODE REVIEW

**Comment by marado** [comment]
I'd rather have the resulting string be something like "1 year, 2 months, 3 days, 5 hours, 5 minutes", instead of what we get with your patch ("1 y 2 m 3 d 5 h 5 m 6s 7ms").

Also, we don't need so much code repetition, the final string can be constructed from inbetween strings (ie: `friendly = "5 minutes"; if (ms < (1000 * 60 * 60 * 24)) friendly = Math.floor(ms / 1000 / 60 / 60) + " hours, " + friendly;` ).

**Comment by subhamskm** [comment]
I updated the code. This time I prevented code repetitions.

**Comment by marado** [comment]
Thank you for your contribution! There are a few other issues tagged as "good first issues", if you wish to spend some more time around TalkerNode's code :-)

https://github.com/marado/TalkerNode/labels/good%20first%20issue

**Comment by subhamskm** [comment]
Thanks @marado

**Pull request closed without merging**
