### PR TITLE
Command  Reworking

### PR DESCRIPTION
**Pull request by neilsb**
Number of changes to the command, but most notably moving the commands out into a single file per command.  To add a new command, simply create a new file in the command subfolder (see template.js) setting the appropriate options.  Commands are loaded on startup unless autoload is set to false.

The passed in command access object allows (or restricts) what commands have access to, and can be further restricted as things progress.

Other changes:
* Commands have a minimum rank required, and users of a lower rank than the command won't see or be able to use it
* The help command builds up its text dynamically from the loaded commands
* Commands names are searched for an exact match first, and if none are found the entered command is checked against all commands to see if it's the start of another command.  If it is, and unique then the command is executed.  If it's not unique a list of possible commands are displayed to the user.
* Command execution is wrapped in try/catch so an error in a command won't bring down the server

### CODE REVIEW

**Comment by marado** [comment]
Wow, thanks for your contribution! 
Everything you describe on this submission are things that I've thought of doing myself (I actually have a WIP patch for "ranks for commands" which I'll probably drop in favour of yourse). 

I still have to read the actual code, but in the meantime I have one thing to point out, regarding commands precedence:
While in most cases the behaviour you describe is what we want (typing .a showing up the list of commands that start by .a so you can choose which one you want to use), sometimes we want commands to have more weight than others. For instance, we want that .w to fallback to .who instead of showing the list of available commands starting with 'w' (.who, .wizlist, ...). I suggest this to be achieved by having a non-mandatory 'weight' propriety on commands, and if it has weight and its weight is bigger than the rest of the commands, than that's the one being chosen.

Do you agree and want to take a stab at it, or do you want to leave that to me?

**Comment by neilsb** [comment]
Yeah, that makes sense.  I'm happy to have a look at that but probably won't be till the end of the week given paid work commitments.  Also working on being able to load/unload/reload commands on dynamically so there's no need to restart the server to make changes.

Once you've reviewed the code let me know what you think about passing the command access object into the commands.   Having the commands in modules means they couldn't access the server parameters so had to pass sockets, etc in somehow.  Not sure if giving commands access to the sockets directly is the best thing or whether the command access should just give the commands functions to perform certain actions on the sockets, etc.  (e.g. write, close, etc).  Guess it depends how much commands are to be "trusted".

**Comment by marado** [comment]
A very quick read on the code, it seems sound.

Testing it shows some issues still (I guess mostly if not all caused by the ranks in commands commit):
.rank fails
.q fails
.say fails
.tell fails
.version fails
.who fails

Also, the rank of many of those commands will be '1' and not '0', but that's a minor thing.

I'd rather have the "do not trust commands" approach, and give them access only to a few specific methods (write, close, etc, as you mention). 

In summary:
* fix the commands failures - mandatory for patch to go in
* commands weight - to be turned into an issue to be solved later
* rework commands access to sockets - to be turned into an issue to be solved later
* review commands' ranks - to be turned into an issue to be solved later
* redo the .promote branch - on my TODO list already :-)

I'll see if I have the time to look into fixing the commands failures and merge your pull request before the weekend. If so, I'll create the issues described above, and you feel free to pick up on them :-)

Thanks

**Comment by marado** [comment]
https://github.com/marado/TalkerNode/tree/neil has this pull request + part of the fix for commands failures. .password is still messing up with the entire talker, that needs to be fixed before the branch gets merged.

**Comment by marado** [comment]
OK, this was merged (with changes), thanks a lot for your contribution!

There are a few leftovers that are now turned into issues ( https://github.com/marado/TalkerNode/issues ) - feel free to assign yourself to any of them, I hope you're willing to keep up contributing!

**Pull request closed without merging**
